version: '3'

services:
    site:
        build:
            context: ./services/site
            args:
                DOCKER_USER_NAME: ${DOCKER_USER_NAME}
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        user: ${DOCKER_USER_ID}:${DOCKER_GROUP_ID}
        tty: true
        command: ["bash", "-c", ## need to run multiple command '&&'
                "bundle install && bundle exec jekyll serve -H 0.0.0.0"
        ]
        ports:
            - '80:4000'
        volumes:
            - '/etc/passwd:/etc/passwd:ro'
            - '/etc/group:/etc/group:ro'
            - './:/home/code'
            - '.bundle/:/home/${DOCKER_USER_NAME}/.bundle'
            - 'bloggemsbin:/usr/local/bundle'

volumes:
    bloggemsbin:
